steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: sh
    secretEnv: ['GITHUB_TOKEN']
    args:
      - '-c'
      - >

        git config --global credential.helper 'store --file=/tmp/creds'

        echo "https://$$GITHUB_TOKEN:x-oauth-basic@github.com" > /tmp/creds

        git clone https://github.com/nektria/__PROJECT__.git 

        git fetch --unshallow --quiet

  - id: Load PHP image
    name: gcr.io/cloud-builders/docker
    args: [ "pull", "-q", "eu.gcr.io/nektria/php:8.3" ]

  - id: Load test services
    name: 'docker/compose'
    entrypoint: sh
    args:
      - '-c'
      - >

        set -e

        echo "Building tests services"

        docker-compose -f server/pipeline/cloudbuild-services.yml up -d 

  - id: validating code
    name: eu.gcr.io/nektria/php:8.3
    entrypoint: sh
    args: [ "/app/pipeline", "$BRANCH_NAME", "$_APP" ]

  - id: Push new __PROJECT__ image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - >

        set -e  >/dev/null 2>&1

        SERIAL_NUMBER=$(git rev-list --count HEAD)

        if [ "$BRANCH_NAME" = "$_BRANCH" ];then TAG=v$$SERIAL_NUMBER; else TAG="v$$SERIAL_NUMBER-$BRANCH_NAME"; fi; >/dev/null 2>&1

        IMAGE=eu.gcr.io/$PROJECT_ID/$_APP:$$TAG  >/dev/null 2>&1

        docker build -t $$IMAGE -f /workspace/server/pipeline/Dockerfile .

        docker push $$IMAGE  >/dev/null 2>&1

        echo Version: eu.gcr.io/nektria/$_APP:$$TAG

substitutions:
  _BRANCH: main
  _APP: __PROJECT__

availableSecrets:
  secretManager:
    - versionName: projects/73093926400/secrets/GITHUB_TOKEN/versions/latest
      env: 'GITHUB_TOKEN'
