services:
  php-sdk:
    image: eu.gcr.io/nektria/php:8.1
    container_name: php-sdk
    restart: 'no'
    networks:
      - default
    volumes:
      - ../../.:/app
      - /app/var
    stdin_open: true
    tty: true
    command: bash

