parameters:

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      string $alertsToken: 'none'
      string $env: '%kernel.environment%'
      string $project: 'sdk'
      string $redisDsn: 'none'

  Nektria\Console\:
    resource: '../src/Console'
    tags: [ 'console.command' ]
    calls:
      - inject: [ '@service_container' ]

  Nektria\Infrastructure\UserServiceInterface: '@Nektria\Service\UserService'
  Nektria\Service\AlertService: ~
  Nektria\Service\Bus: ~
  Nektria\Service\ContextService: ~
  Nektria\Service\HealthService: ~
  Nektria\Service\LogService: ~
  Nektria\Service\RequestClient: ~
  Nektria\Service\RoleManager: ~
  Nektria\Service\SharedDiscordCache: ~
  Nektria\Service\SharedLogCache: ~
  Nektria\Service\SharedTenantCache: ~
  Nektria\Service\SharedUserCache: ~
  Nektria\Service\SharedVariableCache: ~
  Nektria\Service\UserService: ~
  Nektria\Test\TestRunnerListener: ~

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
