services:
  php-sdk:
    build:
      context: ../../.
      dockerfile: server/php-sdk-dev/Dockerfile
    container_name: php-sdk
    restart: 'unless-stopped'
    networks:
      - default
    volumes:
      - ../../.:/app
      - /app/var
    stdin_open: true
    tty: true
    command: bash

